#!/usr/bin/env sh

# Generate the `_CoqProject` file
echo "# !!!" > _CoqProject
echo "# Generated by configure.sh" >> _CoqProject
echo "# !!!" >> _CoqProject
echo "-R src CoqChess" >> _CoqProject
echo >> _CoqProject
find src -name "*.v" |sort >> _CoqProject

# Generate the Makefile
coq_makefile -f _CoqProject -o Makefile
