name: CI

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml-compiler:
          - 4.14.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install . --deps-only
      - run: opam exec -- dune build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/default/bin/web